default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: donut-review_development

test:
  <<: *default
  database: donut-review_test

production:
  <<: *default
  database: donut-review_production
  username: donut-review
  password: <%= ENV['DONUT-REVIEW_DATABASE_PASSWORD'] %>
