# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c7a8981c72326d60ba057a3d54cf85dc067a7a9bdfb114b66345e35eee452d69c5626b283732afe6c34b5fee818a7267ed8b7f3d2367029ddf0d3a0f3521d9d

test:
  secret_key_base: 26e0f1f2ab43211255c809124461dae88f4bcbc6e7ffddd1583d2b9ec5af35e42a4eefb0d2486ec703868eba0b1b7cd2b56c62d8850aaf8bfc85e19142f8aef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
